language: node_js
script: npm run build
notifications:
  email: false
  slack:
    rooms:
      secure: bT3rdg0aAnHA1j8NGlFGoY9Ejqk7cWDfppBym99vi8RTR0pKw2xPN4YfswVIgIzwOWnkFGW8w8OFSn0RP4B/EwrM5TufisgCDLyE4PHDGHOMSDM+utw6uDXc7vKGM3kxaJAw3kRCE49BUla5s98N03Aue2LoLtdE02nDsrAoO9kZTMzi2VuQ4ZXwZ0RyTT+Wo778z+JehRsK6KIgn50FcZe2rWi4wG177zHuLusT0cjhSA01cTBRIYPLB9AEwMwoBX3vOaH8wMwAa6HZa0STqIIViXP1iepK5P11em/VyKlFQaPuKzYJaKB+sxMwfOi7N6bR4eLj6CiQwEJbmQhMgAonp1nGJQWYc/oR5H1gyY9nlxTTGJv5DiNKfuJnC0K658KQK3y9AUuVTx0Sn2RNEjSn1fsfS2GpenOLtdJrX09TfXHQFJ2nTThQvY2UaCuN3AHNxC8Z59fTkcTqKj/He4rC2Ul5ciTavhjlfxmdUXwrw3XgAFn6Sp9YYoMdg4vruIypzvVZWqgIzdEnYjzpmR2npYPWZKjEf18Oq1gQ0Sa7movlaSTA0no/bBxDTyOCZnewmhMrxbcgEAxwxI/qeBsMZQcxfTaGa/2pDUUlm4LpEshV+4hP+HGSyup1ZjMjBf21PipjYkEa8CfLnKkfBrzfp+jRGCzb0eyaZQrdC/g=
